# Generated by Django 5.1.5 on 2025-01-16 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_coupon_allocated_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(default='Default Coupon', max_length=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='allocated_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
