# Generated by Django 5.1.5 on 2025-02-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_coupon_name_alter_coupon_allocated_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_availed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
